name = "UniswapTools"
uuid = "04a251f3-2e37-4697-8021-eba8fd10c8fa"
authors = ["jrab227@gmail.com <jrab227@gmail.com>"]
version = "0.1.0"

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
